const computerMCQs = [
    {
        id: 1,
        question: "Which is NOT an example of an operating system?",
        option1: "Linux",
        option2: "Windows",
        option3: "Photoshop",
        option4: "macOS",
        answer: "Photoshop",
        questionType: "MCQs",
        category: "exercise",
        subject: "computer",
        importance: "important",
        chapter: "1",
        trim: true,
        index: true,
        pastPaper: false,
    },
    {
        id: 2,
        question: "In multi-user environments, the OS ensures:",
        option1: "Equal access and data privacy",
        option2: "All users share the same files",
        option3: "Hardware is never used",
        option4: "Internet speed is increased",
        answer: "Equal access and data privacy",
        questionType: "MCQs",
        category: "exercise",
        subject: "computer",
        importance: "important",
        chapter: "1",
        trim: true,
        index: true,
        pastPaper: false,
    },
    {
        id: 3,
        question: "In Windows, user accounts can be created via:",
        option1: "Task Manager",
        option2: "Control Panel or Settings",
        option3: "Disk Management",
        option4: "BIOS settings",
        answer: "Control Panel or Settings",
        questionType: "MCQs",
        category: "exercise",
        subject: "computer",
        importance: "important",
        chapter: "1",
        trim: true,
        index: true,
        pastPaper: false,
    },
    {
        id: 4,
        question: "The core part of the OS that interacts directly with hardware is the:",
        option1: "Shell",
        option2: "Kernel",
        option3: "Device Driver",
        option4: "System Library",
        answer: "Kernel",
        questionType: "MCQs",
        category: "exercise",
        subject: "computer",
        importance: "important",
        chapter: "1",
        trim: true,
        index: true,
        pastPaper: false,
    },
    {
        id: 5,
        question: "A graphical shell allows the user to:",
        option1: "Type commands only",
        option2: "Click icons and use menus",
        option3: "Interact only via code",
        option4: "Access only the BIOS",
        answer: "Click icons and use menus",
        questionType: "MCQs",
        category: "exercise",
        subject: "computer",
        importance: "important",
        chapter: "1",
        trim: true,
        index: true,
        pastPaper: false,
    },
    {
        id: 6,
        question: "In the FCFS scheduling method, processes are served:",
        option1: "Randomly",
        option2: "Shortest job first",
        option3: "In the order they arrive",
        option4: "By priority only",
        answer: "In the order they arrive",
        questionType: "MCQs",
        category: "exercise",
        subject: "computer",
        importance: "important",
        chapter: "1",
        trim: true,
        index: true,
        pastPaper: false,
    },
    {
        id: 7,
        question: "Threads in the same process:",
        option1: "Have separate memory spaces",
        option2: "Share the same memory and resources",
        option3: "Run on different OS",
        option4: "Cannot run simultaneously",
        answer: "Share the same memory and resources",
        questionType: "MCQs",
        category: "exercise",
        subject: "computer",
        importance: "important",
        chapter: "1",
        trim: true,
        index: true,
        pastPaper: false,
    },
    {
        id: 8,
        question: "Which system call is used to create a new process?",
        option1: "Open",
        option2: "Read",
        option3: "Write",
        option4: "Fork",
        answer: "Fork",
        questionType: "MCQs",
        category: "exercise",
        subject: "computer",
        importance: "important",
        chapter: "1",
        trim: true,
        index: true,
        pastPaper: false,
    },
]

export { computerMCQs }