const computerShortQuestions = [
    {
    id: 1,
    question: "Why is the operating system referred to as the central controller?",
    questionType: "Short",
    chapter: "1",
    category: "exercise",
    subject: "computer",
    importance: "important",
    chapter: "1",
    trim: true,
    index: true,
    pastPaper: false,
},
{
    id: 2,
    question: "How does the OS act as a translator between the user and hardware?",
    questionType: "Short",
    category: "exercise",
    subject: "computer",
    importance: "important",
    chapter: "1",
    trim: true,
    index: true,
    pastPaper: false,
},
{
    id: 3,
    question: "Define one way to create a new user account in Windows?",
    questionType: "Short",
    category: "exercise",
    subject: "computer",
    importance: "important",
    chapter: "1",
    trim: true,
    index: true,
    pastPaper: false,
},
{
    id: 4,
    question: "How is kernel different from shell?",
    questionType: "Short",
    category: "exercise",
    subject: "computer",
    importance: "important",
    chapter: "1",
    trim: true,
    index: true,
    pastPaper: false,
},
{
    id: 5,
    question: "Give one example of a system library and its purpose?",
    questionType: "Short",
    category: "exercise",
    subject: "computer",
    importance: "important",
    chapter: "1",
    trim: true,
    index: true,
    pastPaper: false,
},
{
    id: 6,
    question: "Explain one advantage and one disadvantage of FCFS scheduling?",
    questionType: "Short",
    category: "exercise",
    subject: "computer",
    importance: "important",
    chapter: "1",
    trim: true,
    index: true,
    pastPaper: false,
},
{
    id: 7,
    question: "Why is virtual memory slower than RAM?",
    questionType: "Short",
    category: "exercise",
    subject: "computer",
    importance: "important",
    chapter: "1",
    trim: true,
    index: true,
    pastPaper: false,
},
{
    id: 8,
    question: "Define a system call?",
    questionType: "Short",
    category: "exercise",
    subject: "computer",
    importance: "important",
    chapter: "1",
    trim: true,
    index: true,
    pastPaper: false,
},
{
    id: 9,
    question: "What is the role of a file system?",
    questionType: "Short",
    category: "exercise",
    subject: "computer",
    importance: "important",
    trim: true,
    index: true,
    pastPaper: false,
},
{
    id: 10,
    question: "Define multitasking in computer system?",
    questionType: "Short",
    category: "exercise",
    subject: "computer",
    importance: "important",
    trim: true,
    index: true,
    pastPaper: false,
},
]

export { computerShortQuestions }